FROM docker.io/maven:3.9.9-eclipse-temurin-17

USER root

ARG MAVEN_HTTPS_PROXY
ARG HTTPS_PROXY
ARG HTTP_PROXY
ARG DEPLOYMENT_ENVIRO

ENV MAVEN_HTTPS_PROXY=$MAVEN_HTTPS_PROXY
ENV HTTPS_PROXY=$HTTPS_PROXY
ENV HTTP_PROXY=$HTTP_PROXY
ENV DEPLOYMENT_ENVIRO=${DEPLOYMENT_ENVIRO}

ARG GIT_URL
ARG GIT_COMMIT

ENV GIT_URL=${GIT_URL}
ENV GIT_COMMIT=${GIT_COMMIT}

RUN apt -y install git curl
RUN git config --global http.sslVerify false

WORKDIR /opt/

RUN git clone --recurse-submodules -b master ${GIT_URL}

WORKDIR /opt/yamcs

RUN git checkout ${GIT_COMMIT}

ENV YAMCS_EXAMPLE="cfdp"

RUN mvn -f "examples/${YAMCS_EXAMPLE}/pom.xml" package yamcs:bundle
